# render.yaml - 修正版

services:
  # 定义一个Web服务
  - type: web
    # 服务的唯一名称
    name: fatigue-detector-a191610
    # 运行环境
    env: python
    # 套餐类型
    plan: free
    # 构建命令 (安装依赖)
    buildCommand: "pip install -r requirements.txt"
    # 启动命令 (用Gunicorn启动您的Flask应用)
    startCommand: "gunicorn backend_server:app"
    # 自动部署设置
    autoDeploy: true
    # 健康检查路径
    healthCheckPath: /